### ISSUE TITLE
expose `trasnformMatrix` parameter for `SpriteBatch.Begin`, for easier camera work

### ISSUE THREAD

**Issue by tupini07** [BenMakesGames/PlayPlayMini#4]
Hi! This is more of a question than an issue but I noticed that the project has no `discussions` tab, so forgive me for asking it here :P 

I was wondering if there's a proper way to get a camera-like effect in PlayPlayMini? The obvious would be to just keep an offset somewhere in my own code apply it to all Draw calls I make. 

But I was wondering if there was perhaps another (easier) way? I know MonoGame offers a `transformMatrix` parameter in `SpriteBatch.Begin` can be used to offset all draw calls (among other things), but this doesn't seem to be exposed in PlayPlayMini.

Another way I can think of is to "draw" all my stuff to a texture and then render that texture with an offset. But that seems to be getting around some of the design of playplaymini 🤔 so it doesn't feel very _nice_.

**Comment by BenMakesGames** [comment]
I've always handled the camera the first way you described: by applying camera offsets to draw calls myself... that said, I was not aware of the `transformMatrix` parameter for `SpriteBatch.Begin`, and I can see how that would reduce some manual adding/subtracting!

exposing the `transformMatrix` parameter feels pretty reasonable. not sure when I'll get to it, but let's leave this issue open for that!

**Comment by tupini07** [comment]
cool, thanks! I could try to take a stab at this if you want. I'm just unsure about where it would be best to expose this. The first idea that comes to mind is adding an optional `TransformMatrix` field to the `GraphicsManager`, which is used if set. I'm not super familiar with PlayPlayMini's code, but this approach seems nice since it prevents having to muck around with the current 
 scene's "lifetime loop" (update + draw).

Another idea, which is more involved but possibly would provide better dev experience, is that `GraphicManager` can have an `ICamera?` (or similar) which knows how to get the current transform matrix. This would also allow for PlayPlayMini to provide a simple camera implementation as well as allow other people to add their own.

Now, there's also the question of whether making it possible to set `transformMatrix` will now make `GraphicsManager.Zoom` redundant, since the Zoom can be set at the matrix/camera level. 

What do you think? Do you have any better ideas?

**Comment by BenMakesGames** [comment]
having some way to specify a `TransformMatrix` for the `GraphicsManager` makes sense.

I have mixed feelings about an `ICamera`... I do end up making camera logic for my games, but I feel like the camera needs can be very different from game to game.

`Zoom` scales up/down all the graphics, and the game window, so is a different thing entirely. example from Word x Word (available on Steam! made with PlayPlayMini! :P)

![zoom](https://github.com/BenMakesGames/PlayPlayMini/assets/1587505/36f74547-fdd7-44dc-a31f-e8b4ae525fae)

**Comment by tupini07** [comment]
> I have mixed feelings about an ICamera... I do end up making camera logic for my games, but I feel like the camera needs can be very different from game to game.

ok makes sense! I guess folks can also have their own camera and pass the 'transformMatrix" to the graphics manager when needed. Better separation of concerns as well.


> Zoom scales up/down all the graphics, and the game window, so is a different thing entirely. example from Word x Word (available on Steam! made with PlayPlayMini! :P)

oh I see! I hadn't played with this value before, so I let myself assume it was for zooming into the texture and not changing the whole window. 


> having some way to specify a TransformMatrix for the GraphicsManager makes sense.

yeah that's also probably the simplest solution :) I'll take a stab at it later today.

**Comment by BenMakesGames** [comment]
closed by #5
